apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omr-scanner-pvc
  namespace: omr-scanner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
